-- CakeCraft Studio - simulated/demo payments (one record per order)
--
-- University-project payment system: no real payment provider is involved,
-- and no real card data (number, CVV, expiry, cardholder credentials) is
-- ever collected or stored anywhere in this schema. `simulated_reference`
-- is a fake, clearly non-financial demo reference generated by the
-- application (see app/services/payment_service.py), never a real
-- transaction/authorization id.
--
-- Payment status is intentionally separate from orders.status (the
-- production lifecycle): "did they pay" and "where's the cake" are
-- different questions. unique(order_id) enforces exactly one payment
-- record per order, the DB-level half of payment_service.simulate_payment's
-- idempotency guarantee (the other half is its own conditional update).

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders (id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed')),
  amount numeric(10, 2) not null check (amount >= 0),
  simulated_reference text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

alter table public.payments enable row level security;
